name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ${{ secrets.abivarmang }}/nodejs-demo-app:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.Abi@2003}}" | docker login -u "${{ secrets.abivarmang }}" --password-stdin

      - name: Push to DockerHub
        run: docker push ${{ secrets.abivarmang }}/nodejs-demo-app:latest
